import 'package:flutter/material.dart';
import 'package:theme_provider/theme_provider.dart';

get themesData => [
      AppTheme(
        id: "dark_teal",
        description: "Dark Teal Theme",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.dark,
            primary: Color.fromARGB(255, 0, 100, 95),
            onPrimary: Color.fromARGB(255, 200, 255, 250),
            secondary: Color.fromARGB(255, 2, 59, 56),
            onSecondary: Color.fromARGB(255, 200, 255, 250),
            error: Colors.grey,
            onError: Colors.red,
            background: Color.fromARGB(255, 48, 48, 48),
            onBackground: Color.fromARGB(255, 200, 255, 250),
            surface: Color.fromARGB(255, 15, 31, 26),
            onSurface: Color.fromARGB(255, 235, 255, 253),
          ),
        ),
      ),
      AppTheme(
        id: "light_teal",
        description: "Light Teal Theme",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.light,
            primary: Color.fromARGB(255, 0, 140, 133),
            onPrimary: Color.fromARGB(255, 0, 0, 0),
            secondary: Color.fromARGB(100, 0, 174, 165),
            onSecondary: Color.fromARGB(255, 0, 38, 35),
            error: Colors.red,
            onError: Colors.red,
            background: Color.fromARGB(255, 241, 241, 241),
            onBackground: Color.fromARGB(255, 0, 116, 106),
            surface: Colors.white,
            onSurface: Color.fromARGB(255, 0, 28, 25),
          ),
        ),
      ),
      AppTheme(
        id: "light_purple",
        description: "Light Purple Theme",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.light,
            primary: Color.fromARGB(255, 137, 116, 210),
            onPrimary: Color.fromARGB(255, 0, 0, 0),
            secondary: Color.fromARGB(255, 155, 137, 219),
            onSecondary: Color.fromARGB(255, 200, 255, 250),
            error: Colors.grey,
            onError: Colors.red,
            background: Color.fromARGB(255, 241, 241, 241),
            onBackground: Color.fromARGB(255, 85, 0, 128),
            surface: Colors.white,
            onSurface: Color.fromARGB(255, 25, 0, 38),
          ),
        ),
      ),
      AppTheme(
        id: "dark_purple",
        description: "Dark Purple Theme",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.dark,
            primary: Color.fromARGB(255, 94, 78, 148),
            onPrimary: Color.fromARGB(255, 0, 0, 0),
            secondary: Color.fromARGB(255, 58, 51, 82),
            onSecondary: Color.fromARGB(255, 251, 200, 255),
            error: Colors.grey,
            onError: Colors.red,
            background: Color.fromARGB(255, 71, 71, 71),
            onBackground: Color.fromARGB(255, 237, 200, 255),
            surface: Color.fromARGB(255, 40, 28, 44),
            onSurface: Color.fromARGB(255, 254, 244, 255),
          ),
        ),
      ),
      AppTheme(
        id: "dark_pink",
        description: "Dark Pink Theme",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.dark,
            primary: Color.fromARGB(255, 141, 72, 145),
            onPrimary: Color.fromARGB(255, 0, 0, 0),
            secondary: Color.fromARGB(255, 82, 51, 82),
            onSecondary: Color.fromARGB(255, 251, 200, 255),
            error: Colors.grey,
            onError: Colors.red,
            background: Color.fromARGB(255, 71, 71, 71),
            onBackground: Color.fromARGB(255, 237, 200, 255),
            surface: Color.fromARGB(255, 37, 27, 40),
            onSurface: Color.fromARGB(255, 254, 244, 255),
          ),
        ),
      ),
      AppTheme(
        id: "light_pink",
        description: "Light Pink Theme",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.light,
            primary: Color.fromARGB(255, 203, 103, 208),
            onPrimary: Color.fromARGB(255, 0, 0, 0),
            secondary: Color.fromARGB(255, 234, 163, 234),
            onSecondary: Color.fromARGB(255, 200, 255, 250),
            error: Colors.grey,
            onError: Colors.red,
            background: Color.fromARGB(255, 241, 241, 241),
            onBackground: Color.fromARGB(255, 85, 0, 128),
            surface: Colors.white,
            onSurface: Color.fromARGB(255, 25, 0, 38),
          ),
        ),
      ),
      AppTheme(
        id: "light_coffee",
        description: "Light Coffee",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.light,
            primary: Color.fromARGB(255, 115, 81, 38),
            onPrimary: Color.fromARGB(255, 255, 255, 255),
            secondary: Color.fromARGB(255, 255, 227, 181),
            onSecondary: Color.fromARGB(255, 255, 255, 255),
            error: Color.fromARGB(255, 0, 0, 0),
            onError: Colors.red,
            background: Color.fromARGB(255, 255, 250, 239),
            onBackground: Color.fromARGB(255, 0, 0, 0),
            surface: Color.fromARGB(255, 255, 242, 210),
            onSurface: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
      ),
      AppTheme(
        id: "dark_coffee",
        description: "Dark coffee",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.dark,
            primary: Color.fromARGB(255, 115, 81, 38),
            onPrimary: Color.fromARGB(255, 255, 255, 255),
            secondary: Color.fromARGB(255, 68, 58, 40),
            onSecondary: Color.fromARGB(255, 255, 255, 255),
            error: Color.fromARGB(255, 0, 0, 0),
            onError: Colors.red,
            background: Color.fromARGB(255, 29, 27, 24),
            onBackground: Color.fromARGB(255, 255, 255, 255),
            surface: Color.fromARGB(255, 36, 27, 21),
            onSurface: Color.fromARGB(255, 255, 255, 255),
          ),
        ),
      ),
      AppTheme(
        id: "dark_knight",
        description: "Dark Knight",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.dark,
            primary: Color.fromARGB(255, 0, 0, 0),
            onPrimary: Color.fromARGB(255, 255, 255, 255),
            secondary: Color.fromARGB(255, 90, 90, 90),
            onSecondary: Color.fromARGB(255, 255, 255, 255),
            error: Color.fromARGB(255, 0, 0, 0),
            onError: Colors.red,
            background: Color.fromARGB(255, 35, 35, 35),
            onBackground: Color.fromARGB(255, 255, 255, 255),
            surface: Color.fromARGB(255, 56, 56, 56),
            onSurface: Color.fromARGB(255, 255, 255, 255),
          ),
        ),
      ),
      AppTheme(
        id: "light_knight",
        description: "White Knight",
        data: ThemeData(
          useMaterial3: true,
          primaryColor: Colors.blueAccent,
          colorScheme: const ColorScheme(
            brightness: Brightness.light,
            primary: Color.fromARGB(255, 255, 255, 255),
            onPrimary: Color.fromARGB(255, 0, 0, 0),
            secondary: Color.fromARGB(255, 240, 240, 240),
            onSecondary: Color.fromARGB(255, 0, 0, 0),
            error: Color.fromARGB(255, 0, 0, 0),
            onError: Colors.red,
            background: Color.fromARGB(255, 193, 193, 193),
            onBackground: Color.fromARGB(255, 0, 0, 0),
            surface: Color.fromARGB(255, 255, 255, 255),
            onSurface: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
      ),
    ];
